// Code generated by gobind. DO NOT EDIT.

// Java class cn.mapleafgo.mobile.Mobile is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=cn.mapleafgo github.com/Dreamacro/clash/bind/mobile
package cn.mapleafgo.mobile;

import go.Seq;

public abstract class Mobile {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Mobile() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	
	
	public static native void operateTun(boolean enable, int fileDescriptor, int mtu);
	public static native boolean setConfig(String configFile);
	public static native boolean setHomeDir(String homeDir);
	public static native String startRust(String addr);
	public static native boolean startService();
	public static native boolean verifyMMDB(String path);
}
