name: android CD
on:
    push:
        branches:
            - dev
            

jobs:
    rsut-build:
        name: rust-build
        steps:
            - name: Checkout to git repository
              uses: actions/checkout@v4
            
            - name: test
              run: |
                  echo "test"