name: CiCy CD

on:
  push:
    tags:
      - v*

env:
  VERSION_NODE: 20.11.1
  VERSION: 1.1.4
  VERSION_ANDROID_NDK: 27.2.12479018
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          if gh release view "$tag" --repo="${{ github.repository }}" &> /dev/null; then
            echo "Release $tag already exists."
          else
            gh release create "$tag" \
              --repo="${{ github.repository }}" \
              --title="${tag}" \
              --draft \
              --generate-notes
            echo "Release $tag created."
          fi

  desktop-build:
    name: desktop-build
    needs: build_server_connector
    strategy:
      matrix:
        include:
          - os: windows-latest
            command: make:x64
            tag: x64
    runs-on: ${{ matrix.os }}
    env:
      PROJECT_NAME: CiCy
      GITHUB_REPOSITORY: ${{ github.repository }}
      MAKE_OUT_DIR: ${{ github.workspace }}/apps/desktop/out/make
      
    steps:
      - name: Checkout to git repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.VERSION_NODE }}

      - name: Enable Corepack
        run: corepack enable
      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install
      - name: Build Pkg
        run: |
          yarn add bufferutil utf-8-validate @aws-sdk/client-s3

          yarn build:pkg
          cd apps/desktop/public/static/assets
          gh release download ${{ github.ref_name }}
          ls
          cd ../../../../../
          node tools/fix-app.js

      - name: Run build distributive
        uses: borales/actions-yarn@v5
        with:
          cmd: ${{ matrix.command }}
          dir: 'apps/desktop'

      - name: Release Upload assets on Win32
        if: runner.os == 'Windows'
        run: |
          $BUILT_PATH = "${env:MAKE_OUT_DIR}/squirrel.windows/x64/${env:PROJECT_NAME}-${env:VERSION} Setup.exe"
          $OUTPUT_NAME = "${env:MAKE_OUT_DIR}/squirrel.windows/x64/${env:PROJECT_NAME}-v${env:VERSION}-win32-x64 Setup.exe"

          Write-Host "BUILT_PATH: $BUILT_PATH"
          Write-Host "OUTPUT_NAME: $OUTPUT_NAME"

          if (Test-Path "$BUILT_PATH") {
            Move-Item -Force "$BUILT_PATH" "$OUTPUT_NAME"
          } else {
            Write-Error "BUILT_PATH does not exist"
            exit 1
          }
          gh release upload $env:GITHUB_REF_NAME "$OUTPUT_NAME" --clobber

  build_server_connector:
    runs-on: windows-latest
    needs: release
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
          - i686-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build cicy-server
        shell: powershell
        env:
          TARGET: ${{ matrix.target }}
        run: |
          $ARTIFACT_NAME = "cicy-server"
          cd apps-rust/$ARTIFACT_NAME
          cargo build --target $env:TARGET --release
          Set-Location "$env:GITHUB_WORKSPACE"
          $BUILT_PATH = "target/$env:TARGET/release/$ARTIFACT_NAME.exe"
          if (!(Test-Path $BUILT_PATH)) {
            Write-Error "Build output not found at $BUILT_PATH"
            exit 1
          }
          if ("${{ matrix.target }}" -eq "i686-pc-windows-msvc") {
              $TARGET_NAME = "i686"
          } else {
              $TARGET_NAME = "x64"
          }
          $OUTPUT_NAME = "target/$env:TARGET/release/$ARTIFACT_NAME-v${{ env.VERSION }}-win32-$TARGET_NAME.exe"
          Copy-Item $BUILT_PATH $OUTPUT_NAME
          gh release upload ${{ github.ref_name }} $OUTPUT_NAME

      - name: Build cicy-connector
        shell: powershell
        env:
          TARGET: ${{ matrix.target }}
        run: |
          $ARTIFACT_NAME = "cicy-connector"
          cd apps-rust/$ARTIFACT_NAME
          cargo build --target $env:TARGET --release
          Set-Location "$env:GITHUB_WORKSPACE"
          $BUILT_PATH = "target/$env:TARGET/release/$ARTIFACT_NAME.exe"
          if (!(Test-Path $BUILT_PATH)) {
            Write-Error "Build output not found at $BUILT_PATH"
            exit 1
          }

          if ("${{ matrix.target }}" -eq "i686-pc-windows-msvc") {
              $TARGET_NAME = "i686"
          } else {
              $TARGET_NAME = "x64"
          }
          $OUTPUT_NAME = "target/$env:TARGET/release/$ARTIFACT_NAME-v${{ env.VERSION }}-win32-$TARGET_NAME.exe"
          Copy-Item $BUILT_PATH $OUTPUT_NAME
          gh release upload ${{ github.ref_name }} $OUTPUT_NAME


  build_mac_server_connector:
    name: build_mac_server_client for macOS
    runs-on: macos-latest
    needs: release
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build cicy-server
        run: |
          ARTIFACT_NAME=cicy-server
          cd apps-rust/$ARTIFACT_NAME
          cargo build --target ${{ matrix.target }} --release
          cd $GITHUB_WORKSPACE
          BUILT_PATH=target/${{ matrix.target }}/release/$ARTIFACT_NAME

          PLATFORM=$(echo ${{ matrix.target }} | sed 's/.*-//')

          case "${{ matrix.target }}" in
            x86_64-apple-darwin)
              TARGET_NAME=x64
              ;;
            aarch64-apple-darwin)
              TARGET_NAME=arm64
              ;;
          esac
          echo $TARGET_NAME
          OUTPUT_NAME=target/${{ matrix.target }}/release/$ARTIFACT_NAME-v${{ env.VERSION }}-$PLATFORM-$TARGET_NAME
          cp "$BUILT_PATH" "$OUTPUT_NAME"
          gh release upload ${{ github.ref_name }} $OUTPUT_NAME

      - name: Build cicy-connector
        run: |
          ARTIFACT_NAME=cicy-connector
          cd apps-rust/$ARTIFACT_NAME
          cargo build --target ${{ matrix.target }} --release
          cd $GITHUB_WORKSPACE
          BUILT_PATH=target/${{ matrix.target }}/release/$ARTIFACT_NAME
          PLATFORM=$(echo ${{ matrix.target }} | sed 's/.*-//')

          case "${{ matrix.target }}" in
            x86_64-apple-darwin)
              TARGET_NAME=x64
              ;;
            aarch64-apple-darwin)
              TARGET_NAME=arm64
              ;;
          esac
          echo $TARGET_NAME
          OUTPUT_NAME=target/${{ matrix.target }}/release/$ARTIFACT_NAME-v${{ env.VERSION }}-$PLATFORM-$TARGET_NAME
          cp "$BUILT_PATH" "$OUTPUT_NAME"
          gh release upload ${{ github.ref_name }} $OUTPUT_NAME

