name: Android Rust Build

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-cc-agent-rust:
    name: Build cc agent rust
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - armv7-linux-androideabi   # armeabi-v7a
          - aarch64-linux-android     # arm64-v8a
          - x86_64-linux-android      # x86_64

    env:
      ANDROID_NDK_VERSION: 27.2.12479018
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        # ✅ Cache Cargo dependencies
      - name: Cache Cargo registry and build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.target }}-


      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Set up Java (required for sdkmanager)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
    
      
      - name: Cache Android NDK
        uses: actions/cache@v3
        with:
          path: ${{ env.ANDROID_HOME }}/ndk/${{ env.ANDROID_NDK_VERSION }}
          key: ndk-${{ env.ANDROID_NDK_VERSION }}


      - name: Install NDK if not cached
        run: |
          if [ ! -d "$ANDROID_HOME/ndk/$ANDROID_NDK_VERSION" ]; then
            sdkmanager --install "ndk;$ANDROID_NDK_VERSION"
          else
            echo "NDK already cached."
          fi

      - name: Set environment for ${{ matrix.target }}
        run: |
          export TOOLCHAIN=$ANDROID_HOME/ndk/${ANDROID_NDK_VERSION}/toolchains/llvm/prebuilt/linux-x86_64/bin
          API=33
          if [[ "${{ matrix.target }}" == "aarch64-linux-android" ]]; then
            echo "CC_aarch64_linux_android=$TOOLCHAIN/aarch64-linux-android33-clang" >> $GITHUB_ENV
            echo "CXX_aarch64_linux_android=$TOOLCHAIN/aarch64-linux-android33-clang++" >> $GITHUB_ENV
            echo "AR_aarch64_linux_android=$TOOLCHAIN/llvm-ar" >> $GITHUB_ENV
          elif [[ "${{ matrix.target }}" == "armv7-linux-androideabi" ]]; then
            echo "CC_armv7_linux_androideabi=$TOOLCHAIN/armv7a-linux-androideabi33-clang" >> $GITHUB_ENV
            echo "CXX_armv7_linux_androideabi=$TOOLCHAIN/armv7a-linux-androideabi33-clang++" >> $GITHUB_ENV
            echo "AR_armv7_linux_androideabi=$TOOLCHAIN/llvm-ar" >> $GITHUB_ENV
          elif [[ "${{ matrix.target }}" == "x86_64-linux-android" ]]; then
            echo "CC_x86_64_linux_android=$TOOLCHAIN/x86_64-linux-android33-clang" >> $GITHUB_ENV
            echo "CXX_x86_64_linux_android=$TOOLCHAIN/x86_64-linux-android33-clang++" >> $GITHUB_ENV
            echo "AR_x86_64_linux_android=$TOOLCHAIN/llvm-ar" >> $GITHUB_ENV
          fi
          echo "CARGO_TARGET_${{ matrix.target | replace('-', '_') | upper }}_LINKER=${TOOLCHAIN}/${{ matrix.target }}$API-clang" >> $GITHUB_ENV


      - name: Build with cargo for ${{ matrix.target }}
        run: |
          cd apps-rust/cc-agent-rust
          cargo build --target=${{ matrix.target }} --release

      - name: Copy build output to assets with version
        run: |
          mkdir -p assets
          VERSION=$(grep '^version =' Cargo.toml | head -n1 | cut -d '"' -f2)
          echo $VERSION
          ARTIFACT_NAME=cc-agent-rust
          BUILT_PATH=target/${{ matrix.target }}/release/$ARTIFACT_NAME
          OUTPUT_NAME=${ARTIFACT_NAME%}-${{ matrix.target }}-v$VERSION
          cp "$BUILT_PATH" "assets/$OUTPUT_NAME"
          ls -alh assets
