name: Android Rust Build

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-android:
    name: Rust Android Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - armv7-linux-androideabi   # armeabi-v7a
          - aarch64-linux-android     # arm64-v8a
          - x86_64-linux-android      # x86_64

    env:
      ANDROID_NDK_VERSION: 27.2.12479018
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}
      - name: Set up Java (required for sdkmanager)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      - name: Install NDK
        run: |
          sdkmanager --install "ndk;$ANDROID_NDK_VERSION"
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/$ANDROID_NDK_VERSION" >> $GITHUB_ENV
            

      - name: Build with cargo-ndk for ${{ matrix.target }}
        run: |
          cd apps-rus/cc-agent-rust
          cargo ndk -t ${{ matrix.target }} -o ./target/android build --release

      - name: Copy build output to assets with version
        run: |
          mkdir -p assets
          VERSION=$(grep '^version =' Cargo.toml | head -n1 | cut -d '"' -f2)
          echo $VERSION
          ARTIFACT_NAME=cc-agent-rust  # replace this with the actual file name
          BUILT_PATH=target/android/${{ matrix.target }}/release/$ARTIFACT_NAME
          OUTPUT_NAME=${ARTIFACT_NAME%}-${{ matrix.target }}-v$VERSION.so
          cp "$BUILT_PATH" "assets/$OUTPUT_NAME"
          ls -alh assets
