name: CiCy CD

on:
  push:
    branches:
      - test

env:
  VERSION_NODE: 20.11.1
  VERSION: 1.0.85
  VERSION_ANDROID_NDK: 27.2.12479018
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: write

jobs:
  desktop-build:
    name: desktop-build
    needs: build_agent
    strategy:
      matrix:
        include:
          - os: windows-latest
            command: make:x64
            tag: x64
    runs-on: ${{ matrix.os }}
    env:
      PROJECT_NAME: CiCy
      GITHUB_REPOSITORY: ${{ github.repository }}
      MAKE_OUT_DIR: ${{ github.workspace }}/apps/desktop/out/make
      
    steps:
      - name: Checkout to git repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.VERSION_NODE }}
      - name: Build Pkg
        shell: pwsh
        run: |
          $APK_URL = "https://github.com/cicybot/ClashMetaForAndroid/actions/runs/16441645914/artifacts/3586113763"
          Write-Host "Downloading APK from $APK_URL"
          
          # Download the file
          Invoke-WebRequest -Uri $APK_URL -Headers @{ "Authorization" = "Bearer ${{ secrets.GITHUB_TOKEN }}" } -OutFile "app.zip"
          Get-ChildItem
          # Unzip the file
          Expand-Archive -Path "app.zip" -DestinationPath .
          Get-ChildItem
          # Copy APK file (assuming there's only one)
          Get-ChildItem -Filter *.apk | Copy-Item -Destination "app.apk"
          
          # Optional: list files for debugging
          Get-ChildItem


