name: CiCy CD

on:
  push:
    branches:
      - dev

env:
  VERSION_NODE: 20.11.1
  VERSION: 1.0.85
  VERSION_ANDROID_NDK: 27.2.12479018
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: write

jobs:
  desktop-build:
    name: desktop-build
    strategy:
      matrix:
        include:
          - os: windows-latest
            command: make:x64
            tag: x64
    runs-on: ${{ matrix.os }}
    env:
      PROJECT_NAME: CiCy
      GITHUB_REPOSITORY: ${{ github.repository }}
      MAKE_OUT_DIR: ${{ github.workspace }}/apps/desktop/out/make
      
    steps:
      - name: Checkout to git repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.VERSION_NODE }}
      - name: Build Pkg
        shell: pwsh
        run: |
          cd /tmp
          $APK_URL = "https://github.com/cicybot/ClashMetaForAndroid/releases/download/Alpha/cmfa-2.11.14-alpha-universal-release.apk"
          Write-Host "Downloading APK from $APK_URL"
          
          # Download the file
          Invoke-WebRequest -Uri $APK_URL -Headers @{ "Authorization" = "Bearer ${{ secrets.GITHUB_TOKEN }}" } -OutFile "app-v0.0.0.apk"
          Get-ChildItem
          Compress-Archive -Path "app-v0.0.0.apk" -DestinationPath "app-v0.0.0.zip" -Force
          Get-ChildItem





