name: CiCy CD

on:
  push:
    branches:
      - dev


env:
  VERSION_NODE: 20.11.1
  VERSION: 1.0.32
  VERSION_ANDROID_NDK: 27.2.12479018
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: write

jobs:
  build_agent:
    name: Build cicy-agent
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - armv7-linux-androideabi
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4

      - name: Build with cargo
        run: |
          echo $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE

