name: CiCy CD

on:
  push:
    branches:
      - dev

env:
  VERSION_NODE: 20.11.1
  VERSION: 1.0.28
  VERSION_ANDROID_NDK: 27.2.12479018
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: write

jobs:

  
  build_server_client:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4


      - name: Build Pkg
        run: |
          cd apps/desktop/public/static/assets
          gh release download v1.0.31
          echo $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          node tools/fix-app.js
          dir apps/desktop/public/static/assets